# Introducción a la librería Numpy

Numpy es un paquete orientado al análisis matemático y científico de datos, que es uno de los más populares que hay disponibles para Python.


In [1]:
import numpy as np

### Creación de Arrays

In [2]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones # Crea dos matrices de 3x4

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

### Acceder a elementos de una Array

In [3]:
valoraciones[0][1] # Acceder al primer elemento de la primer dimensión y al segundo elemento de la segunda dimensión
# Fila 1 y Columna 2

7

In [4]:
# Notación alternativa

valoraciones[0,1]

7

In [10]:
# Crear un array con mas dimensiones
valoraciones2 = np.array([[[8,7,8,5],[2,6,4,1]],[[8,8,9,5],[8,7,8,5]],[[2,6,8,1],[8,8,9,5]]])
valoraciones2

#   Aquí vamos a tener lo mismo, tres clientes, cuatro productos, uno para cada columna, pero cada cliente habrá valorado estos productos hace un año y este año. Así, con este tipo de estructura, podemos ir incrementando la dimensionalidad de nuestros datos y podemos mantener el tipo de análisis que queremos.

array([[[8, 7, 8, 5],
        [2, 6, 4, 1]],

       [[8, 8, 9, 5],
        [8, 7, 8, 5]],

       [[2, 6, 8, 1],
        [8, 8, 9, 5]]])

In [11]:
# Acceder a los elementos

valoraciones2[0,1,2]

4

### Crear arrays vacios

In [13]:
# Es escalable a cualquier tipo de dimensiones
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Operaciones entre arrays del mismo tamaño

In [14]:
valoraciones2 + np.ones((3,2,4)) # Se le suma un arrays de uno

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7.,  5.,  2.]],

       [[ 9.,  9., 10.,  6.],
        [ 9.,  8.,  9.,  6.]],

       [[ 3.,  7.,  9.,  2.],
        [ 9.,  9., 10.,  6.]]])

### Aplicar la media a todo el Array

In [15]:
np.mean(valoraciones2)

6.083333333333333

### Aplicar la media en un eje especifico de un Array

In [16]:
np.mean(valoraciones2, axis= 0) # Ejecuta para el primer eje
# Con axis = 1, se ejecuta el segundo eje

array([[6.        , 7.        , 8.33333333, 3.66666667],
       [6.        , 7.        , 7.        , 3.66666667]])

### Convertir una lista a un array con las dimensiones que queramos

In [17]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### Usar la funcion de la mediana sobre columnas de DataFrames

In [ ]:
np.median(df["Columna1"])

### Crear objetos aleatorios

In [18]:
np.random.rand(2,2) # Generar un objeto con dos dimensiones, dos filas con dos columnas y con numeros aleatorios entre el 0 y el 1

array([[0.3818433 , 0.05009345],
       [0.25551881, 0.00960857]])