# Preparar los datos para Machine Learning

In [23]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

df = pd.read_csv(r"/home/flavioisay/MEGAsync/Python para data science y big data esencial/base_datos_2008.csv", nrows = 100000)
df = df[["ArrDelay","DepDelay","Distance","AirTime"]].dropna() # Eliminar todos los datos faltantes de las columnas de interés

In [24]:
x_scaled = preprocessing.scale(df) # Escalar los datos con la estandarización
x_scaled # Muestra un array con datos al rededor del 0
# Escala centrada en el cero con una desviación estándar de 1.

array([[-0.63713243, -0.08247884,  0.40657043,  0.4452521 ],
       [-0.12045009,  0.3068154 ,  0.40657043,  0.38990966],
       [ 0.26706167, -0.08247884, -0.26709367, -0.29264705],
       ...,
       [ 1.84940134,  2.18250582,  0.53445243,  0.31611975],
       [ 0.17018373,  0.37759617,  0.53445243,  0.1869874 ],
       [ 0.17018373, -0.25943077,  0.53445243,  0.22388235]])

In [25]:
x_scaled.mean(axis = 0) # Calcular la media para cada una de las columnas
# La media es prácticamente 0

array([2.47651119e-17, 1.07267490e-17, 1.19506063e-16, 1.01364179e-16])

In [15]:
x_scaled.std(axis = 0) # Calcular la desviación estándar para cada una de las columnas
# Muestra que la desviación estándar es 1.

array([1., 1., 1., 1.])

In [26]:
df.iloc[2] # ver retrasos de los vuelos
# Si no se tiene una apreciación de la distribución de los datos no se puede analizar fácilmente


ArrDelay     14.0
DepDelay      8.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [18]:
x_scaled[2] # Como se controla la media y std de todas las variables, se ve que el primer valor está muy por encima de la media y que el segundo valor está muy por debajo de la media.

array([ 0.15146116, -0.05464869, -0.37948664, -0.41546079])

In [27]:
min_max_scaler = preprocessing.MinMaxScaler([0,10]) # Especificar qué rango de valores se quiere tener
x_train_minmax = min_max_scaler.fit_transform(df) # Adaptar basándose en el dataframe
x_train_minmax # Ahora los datos tienen otra escala.
# Es importante cuando se tiene muchos outliers o outliers lejos del centro de la distribución. 

array([[0.77199282, 0.92857143, 3.15557514, 2.91316527],
       [1.05924596, 1.125     , 3.15557514, 2.82913165],
       [1.27468582, 0.92857143, 1.85544293, 1.79271709],
       ...,
       [2.15439856, 2.07142857, 3.4023799 , 2.71708683],
       [1.22082585, 1.16071429, 3.4023799 , 2.5210084 ],
       [1.22082585, 0.83928571, 3.4023799 , 2.57703081]])

In [28]:
df = pd.read_csv(r"/home/flavioisay/MEGAsync/Python para data science y big data esencial/base_datos_2008.csv", nrows=100)
pd.get_dummies(df["Origin"]) # Transformar variables categóricas (aquellas que no son numéricas) a una variable dummie
# Transforma la columna origin en una columna para cada una de las categorías
# Toma 0 en caso de que no sea el aeropuerto
# Toma 1 en caso de que sí lo sea
# Permite enteneder cómo se correlacionan las variables.
# Consume mucha memoria.

IAD  IND  ISP  JAN  JAX  LAS
0     1    0    0    0    0    0
1     1    0    0    0    0    0
2     0    1    0    0    0    0
3     0    1    0    0    0    0
4     0    1    0    0    0    0
..  ...  ...  ...  ...  ...  ...
95    0    0    0    0    0    1
96    0    0    0    0    0    1
97    0    0    0    0    0    1
98    0    0    0    0    0    1
99    0    0    0    0    0    1

[100 rows x 6 columns]